name: Deploy to VPS
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "21"
      - name: Install dependencies
        run: npm install
      - name: Create env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
      - name: Build
        run: npm run build
      - name: Deploy to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          source: "dist/"
          target: ${{ secrets.TARGET_DIR }}
          strip_components: 1
